### PR TITLE
PDF version of Lunar Magic's chm

### PR DESCRIPTION
**Pull request by Fenwolf**
Add a PDF version of Lunar Magic's chm file. This is an arguably easier way to consume Lunar Magic's actually-pretty-good documentation.

Ignore the various other commits that result in no change; I accidentally committed a thing to the wrong branch so I reverted it.

### CODE REVIEW

**Comment by AmperSam-git** [comment]
Is it easier to consume than just opening the help file that comes with LM? 🤔

**Comment by Fenwolf** [comment]
It's obviously subjective but yes I do find it easier to consume a format that has ongoing cross-industry maintenance and support (pdf) that supports ctrl-f search and is completely cross platform compared to a windows-only *deprecated* format that has awful search functionality that hasn't been realistically maintained in any meaningful way for over a decade. 

Feel free to reject though, this was entirely "I find this super duper helpful, maybe the community would too." The original motivation for me doing this conversion at all for myself was when I was completely unable to read the chm in windows 11 for whatever reason.

**Comment by AmperSam-git** [comment]
I'm happy to include it, just wondering. I think maybe putting in the Docs folder might make it more findable though.

**Comment by Fenwolf** [comment]
Good point, I'll send an update later tonight :)

**Pull request merged**
